# First Iterations

## Aim

- Get some nice figs and numbers from early iterations

## 1 - Plate Selection

- Scattering: looks like I tried to measure that

In [1]:
import os
root_path = '../1_PlateSelection/'
file_paths = sorted([os.path.join(root_path, i) for i in os.listdir(root_path)])
file_paths

['../1_PlateSelection/.ipynb_checkpoints',
 '../1_PlateSelection/.~lock.20190603_BM3PostdilutionConcCheck.csv#',
 '../1_PlateSelection/20190603_BM3PostdilutionConcCheck.csv',
 '../1_PlateSelection/20190603_BM3StckConcCheck.csv',
 '../1_PlateSelection/20190603_PlateSelectionAnalysis.py',
 '../1_PlateSelection/20190603_PlateSelectionAnalysis_JustPlotEverything.py',
 '../1_PlateSelection/20190603_PlateSelectionAnalysis_subplotBrach.py',
 '../1_PlateSelection/20190603_PlateselectionTests_ALL.png',
 '../1_PlateSelection/20190604_PlateselectionNotes-1_1.jpg',
 '../1_PlateSelection/20190604_PlateselectionNotes.pdf',
 '../1_PlateSelection/20190604_PlateselectionNotes.txt',
 '../1_PlateSelection/20190604_PlateselectionNotes_2.pdf',
 '../1_PlateSelection/36640.CSV',
 '../1_PlateSelection/36640_2.CSV',
 '../1_PlateSelection/3770bc.CSV',
 '../1_PlateSelection/3770bc_2.CSV',
 '../1_PlateSelection/464718.CSV',
 '../1_PlateSelection/464718_2.CSV',
 '../1_PlateSelection/761860.CSV',
 '../1_PlateSelection/761860_2.CSV',
 '../1_PlateSelection/781620.CSV',
 '../1_PlateSelection/781620_2.CSV',
 '../1_PlateSelection/DELTA.CSV',
 '../1_PlateSelection/DELTA_2.CSV']

In [2]:
from mimetypes import guess_type

csv_paths = [i for i in file_paths if guess_type(i)[0] == 'text/csv']
csv_paths

['../1_PlateSelection/20190603_BM3PostdilutionConcCheck.csv',
 '../1_PlateSelection/20190603_BM3StckConcCheck.csv',
 '../1_PlateSelection/36640.CSV',
 '../1_PlateSelection/36640_2.CSV',
 '../1_PlateSelection/3770bc.CSV',
 '../1_PlateSelection/3770bc_2.CSV',
 '../1_PlateSelection/464718.CSV',
 '../1_PlateSelection/464718_2.CSV',
 '../1_PlateSelection/761860.CSV',
 '../1_PlateSelection/761860_2.CSV',
 '../1_PlateSelection/781620.CSV',
 '../1_PlateSelection/781620_2.CSV',
 '../1_PlateSelection/DELTA.CSV',
 '../1_PlateSelection/DELTA_2.CSV']

In [3]:
spec_data_file_paths = list(filter(lambda x : 'BM3' in x, csv_paths))
spec_data_file_paths

['../1_PlateSelection/20190603_BM3PostdilutionConcCheck.csv',
 '../1_PlateSelection/20190603_BM3StckConcCheck.csv']

In [5]:
import pandas as pd
df = pd.read_csv(spec_data_file_paths[0])
df.head()

,baseline,Unnamed: 1,bm3wthemeDil2uM,Unnamed: 3,bm3wthemeDil5uM1,Unnamed: 5,bm3wthemeDil10uM,Unnamed: 7,Unnamed: 8
0,Wavelength (nm),Abs,Wavelength (nm),Abs,Wavelength (nm),Abs,Wavelength (nm),Abs,NaN
1,799.9971313,-0.0005947110476,799.9971313,0.003252059221,799.9971313,0.003194790101,799.9971313,0.004799798597,NaN
2,798.9984131,-8.665757923E-005,798.9984131,0.004196888767,798.9984131,0.004164531827,798.9984131,0.006426838692,NaN
3,797.9993896,0.001331412699,797.9993896,0.004117882811,797.9993896,0.002651162446,797.9993896,0.005109281279,NaN
4,796.9998779,-0.0004413385177,796.9998779,0.001250459929,796.9998779,0.003601000411,796.9998779,0.004341138527,NaN

In [16]:
def parse_spec(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)
    initial_columns = df.columns 
    wavelength_col_num = df.iloc[0,:].to_list().index('Wavelength (nm)')
    wavelengths_ = df.iloc[:, wavelength_col_num]
    wavelengths = wavelengths_.loc[wavelengths_.str.match('[0-9\.]+')]
    df = df.loc[wavelengths.index, :]
    df = df.loc[:, 1::2]
    return df

parse_spec(spec_data_file_paths[0])

        baseline bm3wthemeDil2uM bm3wthemeDil5uM1 bm3wthemeDil10uM  Unnamed: 8
1    799.9971313     799.9971313      799.9971313      799.9971313         NaN
2    798.9984131     798.9984131      798.9984131      798.9984131         NaN
3    797.9993896     797.9993896      797.9993896      797.9993896         NaN
4    796.9998779     796.9998779      796.9998779      796.9998779         NaN
5            796             796              796              796         NaN
..           ...             ...              ...              ...         ...
597  203.9814758     203.9814758      203.9814758      203.9814758         NaN
598  202.9985199     202.9985199      202.9985199      202.9985199         NaN
599  202.0155182     202.0155182      202.0155182      202.0155182         NaN
600   200.993103      200.993103       200.993103       200.993103         NaN
601  200.0099487     200.0099487      200.0099487      200.0099487         NaN

[601 rows x 5 columns]