In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PlateAnalysis_Echo import PlateDataset

dataset = PlateDataset('20191104_Dopt.CSV','D_Opt.csv')


output =  pd.DataFrame([],columns = [ 'K','percentDMSO', 'Vol','km', 'vmax', 'loss', 'r_squared'])
for i in range(1,19):
    output=output.append(dataset.CalculateMetrics(i))
    
output = output.reset_index(drop=True)
output

           K  percentDMSO   Vol        km      vmax      loss  r_squared
0   1.000000     5.000000  20.0  2.943031  0.041373  0.000089   0.687811
1   2.636364     3.181818  20.0  2.417682  0.054458  0.000128   0.732379
2   4.000000     1.000000  20.0  1.723095  0.085542  0.000379   0.301244
3   4.000000     1.000000  20.0  2.168559  0.079650  0.000065   0.887333
4   1.545455     1.000000  20.0  2.699764  0.055726  0.000052   0.857577
5   1.000000     5.000000  20.0  2.868864  0.024139  0.000218   0.272075
6   2.636364     3.181818  20.0  1.607357  0.070774  0.008810  -0.632209
7   2.636364     5.000000  29.0  2.108251  0.061783  0.000022   0.955862
8   2.636364     5.000000  29.0  1.379805  0.076880  0.000631   0.517902
9   1.000000     2.818182  29.0  2.961471  0.045096  0.000700   0.263986
10  1.000000     2.818182  29.0  2.482838  0.101338  0.000006   0.992719
11  1.000000     5.000000  40.0  3.825840  0.079702  0.000372   0.673269
12  1.000000     1.000000  40.0  3.940536  0.126476  0.002066   0.440584
13  4.000000     5.000000  40.0  4.009533  0.083291  0.000951   0.557764
14  1.000000     5.000000  40.0  4.180866  0.073284  0.000900   0.454079
15  1.000000     1.000000  40.0  3.065386  0.070778  0.000581   0.483868
16  4.000000     1.000000  40.0  0.100278  0.110852  0.001256   0.013848
17  4.000000     1.000000  40.0  0.232253  0.112548  0.000435   0.763050

In [3]:
for i in range(1,19):
    dataset.PlotFigure(i)

Empty DataFrame
Columns: [K, percentDMSO, Vol, km, vmax, loss, r_squared]
Index: []